// Supported country/region list. The lang field is used later when generating intros (Gemini stage).
// tz: IANA timezone, used to convert observed_at (UTC) into the local date for "per day" grouping.
// fetchGeo: geo parameter passed to google-trends-now; null means this geo cannot be fetched directly
//   and must be aggregated from other geos at build time (WW is such a case: google-trends-now
//   returns 0 results for geo='').
// The list covers all 125 countries/regions supported by Google Trends Trending Now (+ WW global aggregate).
export const GEOS = [
  { code: 'WW', name: 'Worldwide',    lang: 'en', tz: 'UTC', fetchGeo: null },
  { code: 'AL', name: 'Albania',                lang: 'sq',    tz: 'Europe/Tirane' },
  { code: 'DZ', name: 'Algeria',                lang: 'ar',    tz: 'Africa/Algiers' },
  { code: 'AO', name: 'Angola',                 lang: 'pt',    tz: 'Africa/Luanda' },
  { code: 'AR', name: 'Argentina',              lang: 'es',    tz: 'America/Argentina/Buenos_Aires' },
  { code: 'AM', name: 'Armenia',                lang: 'hy',    tz: 'Asia/Yerevan' },
  { code: 'AU', name: 'Australia',              lang: 'en',    tz: 'Australia/Sydney' },
  { code: 'AT', name: 'Austria',                lang: 'de',    tz: 'Europe/Vienna' },
  { code: 'AZ', name: 'Azerbaijan',             lang: 'az',    tz: 'Asia/Baku' },
  { code: 'BH', name: 'Bahrain',                lang: 'ar',    tz: 'Asia/Bahrain' },
  { code: 'BD', name: 'Bangladesh',             lang: 'bn',    tz: 'Asia/Dhaka' },
  { code: 'BY', name: 'Belarus',                lang: 'be',    tz: 'Europe/Minsk' },
  { code: 'BE', name: 'Belgium',                lang: 'nl',    tz: 'Europe/Brussels' },
  { code: 'BJ', name: 'Benin',                  lang: 'fr',    tz: 'Africa/Porto-Novo' },
  { code: 'BO', name: 'Bolivia',                lang: 'es',    tz: 'America/La_Paz' },
  { code: 'BA', name: 'Bosnia & Herzegovina',   lang: 'bs',    tz: 'Europe/Sarajevo' },
  { code: 'BR', name: 'Brazil',                 lang: 'pt-BR', tz: 'America/Sao_Paulo' },
  { code: 'BG', name: 'Bulgaria',               lang: 'bg',    tz: 'Europe/Sofia' },
  { code: 'BF', name: 'Burkina Faso',           lang: 'fr',    tz: 'Africa/Ouagadougou' },
  { code: 'KH', name: 'Cambodia',               lang: 'km',    tz: 'Asia/Phnom_Penh' },
  { code: 'CM', name: 'Cameroon',               lang: 'fr',    tz: 'Africa/Douala' },
  { code: 'CA', name: 'Canada',                 lang: 'en',    tz: 'America/Toronto' },
  { code: 'CL', name: 'Chile',                  lang: 'es',    tz: 'America/Santiago' },
  { code: 'CO', name: 'Colombia',               lang: 'es',    tz: 'America/Bogota' },
  { code: 'CD', name: 'Congo - Kinshasa',       lang: 'fr',    tz: 'Africa/Kinshasa' },
  { code: 'CR', name: 'Costa Rica',             lang: 'es',    tz: 'America/Costa_Rica' },
  { code: 'CI', name: "Côte d'Ivoire",          lang: 'fr',    tz: 'Africa/Abidjan' },
  { code: 'HR', name: 'Croatia',                lang: 'hr',    tz: 'Europe/Zagreb' },
  { code: 'CU', name: 'Cuba',                   lang: 'es',    tz: 'America/Havana' },
  { code: 'CY', name: 'Cyprus',                 lang: 'el',    tz: 'Asia/Nicosia' },
  { code: 'CZ', name: 'Czechia',                lang: 'cs',    tz: 'Europe/Prague' },
  { code: 'DK', name: 'Denmark',                lang: 'da',    tz: 'Europe/Copenhagen' },
  { code: 'DO', name: 'Dominican Republic',     lang: 'es',    tz: 'America/Santo_Domingo' },
  { code: 'EC', name: 'Ecuador',                lang: 'es',    tz: 'America/Guayaquil' },
  { code: 'EG', name: 'Egypt',                  lang: 'ar',    tz: 'Africa/Cairo' },
  { code: 'SV', name: 'El Salvador',            lang: 'es',    tz: 'America/El_Salvador' },
  { code: 'EE', name: 'Estonia',                lang: 'et',    tz: 'Europe/Tallinn' },
  { code: 'ET', name: 'Ethiopia',               lang: 'am',    tz: 'Africa/Addis_Ababa' },
  { code: 'FI', name: 'Finland',                lang: 'fi',    tz: 'Europe/Helsinki' },
  { code: 'FR', name: 'France',                 lang: 'fr',    tz: 'Europe/Paris' },
  { code: 'GE', name: 'Georgia',                lang: 'ka',    tz: 'Asia/Tbilisi' },
  { code: 'DE', name: 'Germany',                lang: 'de',    tz: 'Europe/Berlin' },
  { code: 'GH', name: 'Ghana',                  lang: 'en',    tz: 'Africa/Accra' },
  { code: 'GR', name: 'Greece',                 lang: 'el',    tz: 'Europe/Athens' },
  { code: 'GT', name: 'Guatemala',              lang: 'es',    tz: 'America/Guatemala' },
  { code: 'HT', name: 'Haiti',                  lang: 'fr',    tz: 'America/Port-au-Prince' },
  { code: 'HN', name: 'Honduras',               lang: 'es',    tz: 'America/Tegucigalpa' },
  { code: 'HK', name: 'Hong Kong',              lang: 'zh-HK', tz: 'Asia/Hong_Kong' },
  { code: 'HU', name: 'Hungary',                lang: 'hu',    tz: 'Europe/Budapest' },
  { code: 'IN', name: 'India',                  lang: 'en',    tz: 'Asia/Kolkata' },
  { code: 'ID', name: 'Indonesia',              lang: 'id',    tz: 'Asia/Jakarta' },
  { code: 'IR', name: 'Iran',                   lang: 'fa',    tz: 'Asia/Tehran' },
  { code: 'IQ', name: 'Iraq',                   lang: 'ar',    tz: 'Asia/Baghdad' },
  { code: 'IE', name: 'Ireland',                lang: 'en',    tz: 'Europe/Dublin' },
  { code: 'IL', name: 'Israel',                 lang: 'he',    tz: 'Asia/Jerusalem' },
  { code: 'IT', name: 'Italy',                  lang: 'it',    tz: 'Europe/Rome' },
  { code: 'JM', name: 'Jamaica',                lang: 'en',    tz: 'America/Jamaica' },
  { code: 'JP', name: 'Japan',                  lang: 'ja',    tz: 'Asia/Tokyo' },
  { code: 'JO', name: 'Jordan',                 lang: 'ar',    tz: 'Asia/Amman' },
  { code: 'KZ', name: 'Kazakhstan',             lang: 'kk',    tz: 'Asia/Almaty' },
  { code: 'KE', name: 'Kenya',                  lang: 'en',    tz: 'Africa/Nairobi' },
  { code: 'KW', name: 'Kuwait',                 lang: 'ar',    tz: 'Asia/Kuwait' },
  { code: 'KG', name: 'Kyrgyzstan',             lang: 'ky',    tz: 'Asia/Bishkek' },
  { code: 'LV', name: 'Latvia',                 lang: 'lv',    tz: 'Europe/Riga' },
  { code: 'LB', name: 'Lebanon',                lang: 'ar',    tz: 'Asia/Beirut' },
  { code: 'LY', name: 'Libya',                  lang: 'ar',    tz: 'Africa/Tripoli' },
  { code: 'LT', name: 'Lithuania',              lang: 'lt',    tz: 'Europe/Vilnius' },
  { code: 'MY', name: 'Malaysia',               lang: 'ms',    tz: 'Asia/Kuala_Lumpur' },
  { code: 'ML', name: 'Mali',                   lang: 'fr',    tz: 'Africa/Bamako' },
  { code: 'MX', name: 'Mexico',                 lang: 'es',    tz: 'America/Mexico_City' },
  { code: 'MD', name: 'Moldova',                lang: 'ro',    tz: 'Europe/Chisinau' },
  { code: 'MA', name: 'Morocco',                lang: 'ar',    tz: 'Africa/Casablanca' },
  { code: 'MZ', name: 'Mozambique',             lang: 'pt',    tz: 'Africa/Maputo' },
  { code: 'MM', name: 'Myanmar (Burma)',        lang: 'my',    tz: 'Asia/Yangon' },
  { code: 'NP', name: 'Nepal',                  lang: 'ne',    tz: 'Asia/Kathmandu' },
  { code: 'NL', name: 'Netherlands',            lang: 'nl',    tz: 'Europe/Amsterdam' },
  { code: 'NZ', name: 'New Zealand',            lang: 'en',    tz: 'Pacific/Auckland' },
  { code: 'NI', name: 'Nicaragua',              lang: 'es',    tz: 'America/Managua' },
  { code: 'NG', name: 'Nigeria',                lang: 'en',    tz: 'Africa/Lagos' },
  { code: 'MK', name: 'North Macedonia',        lang: 'mk',    tz: 'Europe/Skopje' },
  { code: 'NO', name: 'Norway',                 lang: 'no',    tz: 'Europe/Oslo' },
  { code: 'OM', name: 'Oman',                   lang: 'ar',    tz: 'Asia/Muscat' },
  { code: 'PK', name: 'Pakistan',               lang: 'ur',    tz: 'Asia/Karachi' },
  { code: 'PS', name: 'Palestine',              lang: 'ar',    tz: 'Asia/Gaza' },
  { code: 'PA', name: 'Panama',                 lang: 'es',    tz: 'America/Panama' },
  { code: 'PY', name: 'Paraguay',               lang: 'es',    tz: 'America/Asuncion' },
  { code: 'PE', name: 'Peru',                   lang: 'es',    tz: 'America/Lima' },
  { code: 'PH', name: 'Philippines',            lang: 'en',    tz: 'Asia/Manila' },
  { code: 'PL', name: 'Poland',                 lang: 'pl',    tz: 'Europe/Warsaw' },
  { code: 'PT', name: 'Portugal',               lang: 'pt',    tz: 'Europe/Lisbon' },
  { code: 'PR', name: 'Puerto Rico',            lang: 'es',    tz: 'America/Puerto_Rico' },
  { code: 'QA', name: 'Qatar',                  lang: 'ar',    tz: 'Asia/Qatar' },
  { code: 'RO', name: 'Romania',                lang: 'ro',    tz: 'Europe/Bucharest' },
  { code: 'RU', name: 'Russia',                 lang: 'ru',    tz: 'Europe/Moscow' },
  { code: 'SA', name: 'Saudi Arabia',           lang: 'ar',    tz: 'Asia/Riyadh' },
  { code: 'SN', name: 'Senegal',                lang: 'fr',    tz: 'Africa/Dakar' },
  { code: 'RS', name: 'Serbia',                 lang: 'sr',    tz: 'Europe/Belgrade' },
  { code: 'SG', name: 'Singapore',              lang: 'en',    tz: 'Asia/Singapore' },
  { code: 'SK', name: 'Slovakia',               lang: 'sk',    tz: 'Europe/Bratislava' },
  { code: 'SI', name: 'Slovenia',               lang: 'sl',    tz: 'Europe/Ljubljana' },
  { code: 'ZA', name: 'South Africa',           lang: 'en',    tz: 'Africa/Johannesburg' },
  { code: 'KR', name: 'South Korea',            lang: 'ko',    tz: 'Asia/Seoul' },
  { code: 'ES', name: 'Spain',                  lang: 'es',    tz: 'Europe/Madrid' },
  { code: 'LK', name: 'Sri Lanka',              lang: 'en',    tz: 'Asia/Colombo' },
  { code: 'SE', name: 'Sweden',                 lang: 'sv',    tz: 'Europe/Stockholm' },
  { code: 'CH', name: 'Switzerland',            lang: 'de',    tz: 'Europe/Zurich' },
  { code: 'SY', name: 'Syria',                  lang: 'ar',    tz: 'Asia/Damascus' },
  { code: 'TW', name: 'Taiwan',                 lang: 'zh-TW', tz: 'Asia/Taipei' },
  { code: 'TZ', name: 'Tanzania',               lang: 'en',    tz: 'Africa/Dar_es_Salaam' },
  { code: 'TH', name: 'Thailand',               lang: 'th',    tz: 'Asia/Bangkok' },
  { code: 'TT', name: 'Trinidad & Tobago',      lang: 'en',    tz: 'America/Port_of_Spain' },
  { code: 'TN', name: 'Tunisia',                lang: 'ar',    tz: 'Africa/Tunis' },
  { code: 'TR', name: 'Turkiye',                lang: 'tr',    tz: 'Europe/Istanbul' },
  { code: 'TM', name: 'Turkmenistan',           lang: 'tk',    tz: 'Asia/Ashgabat' },
  { code: 'UG', name: 'Uganda',                 lang: 'en',    tz: 'Africa/Kampala' },
  { code: 'UA', name: 'Ukraine',                lang: 'uk',    tz: 'Europe/Kyiv' },
  { code: 'AE', name: 'United Arab Emirates',   lang: 'ar',    tz: 'Asia/Dubai' },
  { code: 'GB', name: 'United Kingdom',         lang: 'en',    tz: 'Europe/London' },
  { code: 'US', name: 'United States',          lang: 'en',    tz: 'America/New_York' },
  { code: 'UY', name: 'Uruguay',                lang: 'es',    tz: 'America/Montevideo' },
  { code: 'UZ', name: 'Uzbekistan',             lang: 'uz',    tz: 'Asia/Tashkent' },
  { code: 'VE', name: 'Venezuela',              lang: 'es',    tz: 'America/Caracas' },
  { code: 'VN', name: 'Vietnam',                lang: 'vi',    tz: 'Asia/Ho_Chi_Minh' },
  { code: 'YE', name: 'Yemen',                  lang: 'ar',    tz: 'Asia/Aden' },
  { code: 'ZM', name: 'Zambia',                 lang: 'en',    tz: 'Africa/Lusaka' },
  { code: 'ZW', name: 'Zimbabwe',               lang: 'en',    tz: 'Africa/Harare' },
];

export const GEO_BY_CODE = Object.fromEntries(GEOS.map((g) => [g.code, g]));
